protoc --go_out=user --go_opt=paths=source_relative --go-grpc_out=user --go-grpc_opt=paths=source_relative user.proto

protoc --go_out=wallet --go_opt=paths=source_relative --go-grpc_out=wallet --go-grpc_opt=paths=source_relative wallet.proto